# Generated by Django 3.2.9 on 2022-02-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_meetup_organizer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='emil',
            new_name='email',
        ),
    ]
